  version: 1.0.{build}

  environment:
    matrix:
    - COMPILER: msys2
      PLATFORM: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      BIT: 64

  install:
    # running under CI

  build_script:
    - set PATH=C:\msys64\usr\bin;%PATH%
    - cd harib
    - make img

  test_script: