  version: 1.0.{build}

  environment:
    matrix:
    - COMPILER: msys2
      PLATFORM: x86
      MSYS2_ARCH: x86
      MSYS2_DIR: msys32
      MSYSTEM: MINGW32
      BIT: 32

  install:
    # running under CI

  build_script:
    - set PATH=C:\msys32\usr\bin;%PATH%
    - cd harib
    - make img

  test_script: